# Generated by Django 3.1.3 on 2023-02-14 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_auto_20230214_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='path',
            field=models.FileField(default='media/data', upload_to='media/data'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file_name',
            field=models.TextField(default=datetime.datetime.now, max_length=1000),
        ),
    ]
